---
title: "Test R Markdown 2.0"
author: "Jane Huber & Meghan Mokate"
date: "3/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) 
library(rvest)
library(janitor)
```

Create the tibble by importing csv file
```{r}
hourly_comp_net_prod_tb <- read_csv("Data_HourlyCompensation_NetProd.csv")
min_wage_tb <- read_csv("Data_Year_Minwage.csv")

#Fill in the years with their min wages

total_minwage_comp_prod <- left_join(hourly_comp_net_prod_tb, min_wage_tb, by="Year")

total_minwage_comp_prod_r <- 
  total_minwage_comp_prod %>%
  fill(`Minimum Wage`, .direction = "up")

```

Load inflation
```{r}
url <- "https://www.usinflationcalculator.com/inflation/consumer-price-index-and-annual-percent-changes-from-1913-to-2008/"
inflation_source <- url %>%
  html() %>%
  html_nodes(xpath='//*[@id="post-17"]/div/div[1]/table') %>%
  html_table()
inflation_source_1 <- inflation_source[[1]]
inflation <- inflation_source_1 %>%
  row_to_names(row_number = 2) %>%
  select(1, 16) %>%
  rename("Annual Inflation" = 2) %>%
  mutate(Year = as.double(Year), `Annual Inflation` = as.double(`Annual Inflation`))
inflation

master_set <- left_join(total_minwage_comp_prod_r, inflation, by="Year")
```